config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  get '/classics', to: 'pages#classics'
  get '/search', to: 'pages#search'

  resources :users, only: [:index, :show]

  resources :cocktails do
    get 'random', on: :collection
    member do
      post 'remix'
      get 'mark'
      patch 'publish'
    end
    resources :doses, only: [:create, :destroy]
    resources :reviews, except: [:new, :show]
  end

  match '*path' => 'errors#route_404', via: :all

end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  include PgSearch::Model

  belongs_to :user, optional: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :marks
  has_many :markers, through: :marks, source: :user
  has_many :reviews, dependent: :destroy
  has_many :reviewers, through: :reviews, source: :user

  validates :name, presence: true, allow_blank: false
  validates :description, :instructions, presence: true, allow_blank: true

  mount_uploader :photo, PhotoUploader

  pg_search_scope :search_keyword, {
    using: { tsearch: {
      any_word: true,
      prefix: true,
      dictionary: 'english'
    } },
    against: {
      name: 'A',
      description: 'C'
    },
    associated_against: {
      ingredients: { name: 'B' }
    }
  }

  def creator
    user.nil? ? 'Classic Collection' : user.name
  end

  def image_path
    photo.url ? ApplicationController.helpers.cl_image_path(photo.url) : ApplicationController.helpers.cl_image_path('default_cocktail.png')
  end

  def rating
    if reviews.any?
      avg = reviews.map { |r| r.rating }.reduce(:+) / reviews.count.to_f
      (avg * 10).round / 10.0
    else
      0
    end
  end

end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :random]
  before_action :find_cocktail, only: [:show, :edit, :update, :publish, :destroy, :mark]

  after_action :verify_authorized, only: [:edit, :update, :publish, :destroy]
  after_action :verify_policy_scoped, only: :index

  def index
    @search_page, @custom_page = params[:search_page] || 1, params[:custom_page] || 1
    @search_id, @custom_id = 'cocktail-search', 'cocktail-custom'

    # on html or ajax requests
    @cocktails = policy_scope(Cocktail)
    @classic = @cocktails.where(user: nil)
    @custom = @cocktails.where('user_id IS NOT NULL').paginate(page: @custom_page, per_page: cards_pp)
    if params[:search]
      @search_query = params[:search].downcase
      @search_results = Cocktail.search_keyword(@search_query).paginate(page: @search_page, per_page: items_pp)
    end

    # on ajax requests only
    if request.xhr?
      # determine change in search params
      prev_uri = URI.parse(request.referrer)
      @prev_params = prev_uri.query ? CGI.parse(prev_uri.query) : nil
      @change_search = @search_query && (@search_page != (@prev_params && @prev_params.key?('search_page') ? @prev_params['search_page'][0] : 1))
      @change_custom = @custom_page != (@prev_params && @prev_params.key?('custom_page') ? @prev_params['custom_page'][0] : 1)
      # update window url state
      @url = request.original_fullpath.html_safe

    # on html requests only
    else
      if current_user
        @user_cocktails = current_user.cocktails[0,4] if current_user.cocktails.any?
        @marked_cocktails = current_user.marked[0,4] if current_user.marked.any?
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @user_has_reviewed = user_signed_in? && @cocktail.reviewers.include?(current_user)
    if @user_has_reviewed
      @user_review = Review.where(cocktail: @cocktail, user: current_user)[0]
    end
    @review = Review.new
  end

  def random
    redirect_to cocktail_path(Cocktail.all.sample)
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(strong_params)
    @cocktail.user = current_user
    if @cocktail.save
      redirect_to edit_cocktail_path(@cocktail), { notice: "Created #{@cocktail.name}! Here in the cocktail lab, you can add ingredient doses and write fancy mixing instructions. When you're finished, you can publish your recipe to show it off to the community."}
    else
      render :new
    end
  end

  def edit
    authorize @cocktail
    @dose = Dose.new
    @measurements = Measurement.all
  end

  def update
    authorize @cocktail
    flash = !strong_params.empty? && @cocktail.update(strong_params) ? { notice: 'Update success!' } : { alert: 'Update failed.' }
    redirect_to edit_cocktail_path(@cocktail), flash
  end

  def destroy
    authorize @cocktail
    if @cocktail.destroy
      redirect_to cocktails_path, notice: "#{@cocktail.name} recipe successfully deleted."
    else
      redirect_to :edit, alert: "Unable to delete #{@cocktail.name}: #{@cocktail.errors.full_messages.join(' ')}"
    end
  end

  def remix
    if request.post?
      @cocktail = Cocktail.find(params[:id])
      # prepare remix with new doses
      @remix = Cocktail.new(@cocktail.attributes.slice('name', 'description', 'photo', 'instructions'))
      @remix.name = "Remix of #{@remix.name}"
      @remix.user = current_user

      @doses = @cocktail.doses.map do |d|
        copy = Dose.new(d.attributes.slice('amount', 'ingredient_id', 'measurement_id'))
        copy.cocktail = @remix
        copy
      end

      begin
        Cocktail.transaction do
          @remix.save!
          @doses.each { |d| d.save! }
        end
        # successful saves, redirect to
        redirect_to edit_cocktail_path(@remix), notice: "Successfully remixed! Here in the lab, you can customize your new recipe."
      rescue ActiveRecord::RecordInvalid => invalid
        redirect_to :back, alert: "Failed to remix: #{invalid.record.errors.full_messages.join(' ')}"
      end
    else
      record_not_found
    end
  end

  # ajax
  def publish
    authorize @cocktail
    @cocktail.update(published: !@cocktail.published)
    redirect_options = { alert: "Failed to update: #{@errors.full_messages.join(' ')}" } if @cocktail.errors.any?
    respond_to do |format|
      format.html { redirect_to request.referrer, redirect_options || {} }
      format.js
    end
  end

  # ajax
  def mark
    if current_user.marked.include? @cocktail
      # delete mark if exists
      mark = Mark.where(user: current_user, cocktail: @cocktail)[0]
      if !mark.destroy
        @errors = mark.errors
      end
    else
      mark = Mark.new(user: current_user, cocktail: @cocktail)
      if !mark.save
        @errors = mark.errors
      end
    end

    redirect_options = { alert: "Failed to update: #{@errors.full_messages.join(' ')}" } if @errors && @errors.any?

    respond_to do |format|
      format.html { redirect_to request.referrer, redirect_options || {} }
      format.js
    end
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def strong_params
    params.require(:cocktail).permit(:name, :description, :photo, :instructions, :published)
  end

end

app/helpers/cocktails_helper.rb
module CocktailsHelper

end

app/views/cocktails/edit.html.erb
<!-- banner -->
<div class="cover-image padding-all" <%= render_bg_img(cl_image_path('cocktail_lab.png')) %>>
  <!-- banner content -->
  <div class="ui basic fluid segment">
    <div class="margin-top">
      <h1 class="ui center aligned inverted icon header">
        <i class="tiny circular inverted flask icon transform-sm"></i>
        <em>The Cocktail Lab</em>
      </h1>
    </div>
  </div>
</div>

<div class="ui container">

  <!-- header -->

  <div class="cocktail-overlapping-header padding-left">
    <div class="img-sq-circle cocktail-avatar flex_static">
      <img src="<%= @cocktail.image_path %>" alt="<%= @cocktail.name %>">
    </div>
    <div class="flex_fluid margin-left">
      <div class="ui basic secondary segment">
        <h2 class="ui huge sub header"><%= @cocktail.name %></h2>
        <p class="description"><%= @cocktail.description %></p>
      </div>
    </div>
  </div>

  <!-- edit content -->
  <div class="ui raised segment">

    <!-- actions container -->
    <div class="stamp--top--right margin-right cocktail-lab-actions">
      <!-- hidden form for cocktail/publish -->
      <%= form_with url: publish_cocktail_path(@cocktail), method: :patch, remote: true, id: 'publish-form', class: 'hide' do %><% end %>
      <!-- actions -->
      <div class="ui compact labeled icon menu">
        <%= link_to '#', id: 'publish-link', class: 'item' do %>
          <% published = @cocktail.published %>
          <i class="<%= published ? 'green book' : 'grey book' %> icon"></i>
          <span>Publish<%= published ? 'ed' : '' %></span>
        <% end %>
        <%= link_to cocktail_path(@cocktail), class: 'item' do %>
          <i class="teal icon">
            <i class="icons">
              <i class="file alternate icon"></i>
              <i class="bottom right corner eye icon"></i>
            </i>
          </i>
          View
        <% end %>
        <%= link_to remix_cocktail_path(@cocktail), method: :post, class: 'item' do %>
          <i class="purple icon">
            <i class="icons">
              <i class="flask icon"></i>
              <i class="top right corner shuffle icon"></i>
            </i>
          </i>
          Remix
        <% end %>
        <%= link_to cocktail_path(@cocktail), method: 'delete', class: 'item', data: { confirm: "Delete #{@cocktail.name} recipe?" } do %>
          <i class="red trash icon"></i>
          Delete
        <% end %>
      </div>
    </div>

    <!-- info -->
    <div class="ui red ribbon label">
      <i class="caret right icon"></i>
      Cocktail Profile
    </div>

    <div class="ui basic segment">
      <%= simple_form_for @cocktail, method: :patch, html: { id: 'cocktail-form', class: 'ui form' } do |f| %>
        <div class="ui two column stackable grid">
          <div class="column">
            <%= f.input :name, wrapper_html: { class: 'field validate--empty' } %>
            <%= f.input :description, as: :text, wrapper_html: { class: 'field validate--empty' }, input_html: { rows: 3, placeholder: 'Write a brief description...' } %>
          </div>
          <div class="column">
            <%= f.input :photo, as: :file, wrapper_html: { class: 'field flex_fluid' }, input_html: { id: 'cocktail_photo', class: 'image-upload-preview' } %>
            <%= f.input :photo_cache, as: :hidden %>
            <div class="flex-col-middle">
              <div id="cocktail_photo-preview" class="img-sq-sm-circle flex_static margin-all hide"> </div>
            </div>
          </div>
        </div>
        <div class="margin-top">
          <%= f.submit "Update", class: 'ui red button' %>
        </div>
      <% end %>
    </div>


    <!-- mix doses -->
    <div class="ui blue ribbon label">
      <i class="caret right icon"></i>
      Mixology
    </div>

    <div class="ui basic segment">

      <div id="dose-list" class="ui segment">
        <div class="ui top attached label">Dosage</div>
        <% if @cocktail.doses.empty? %>
          <%= render partial: 'static/no_doses_message' %>
        <% else %>
          <% @cocktail.doses.each do |dose| %>
            <%= render partial: 'shared/dose_chip', locals: { dose: dose } %>
          <% end %>
        <% end %>
      </div>
      <!-- dose form -->
      <div class="ui segment">
        <div class="ui top attached label">New Dose</div>
        <%= simple_form_for [@cocktail, @dose], remote: true, html: { id: 'dose-form', class: 'ui form'} do |f| %>
          <!-- form inputs -->
          <div class="two fields">
            <!-- ingredient input -->
            <%= f.input :ingredient, wrapper_html: { class: 'field validate--empty' }, input_html: { id: "dose-form-ingredient" } %>

            <div class="field flex-row">
              <!-- amount -->
              <div class="flex_fluid field">
                <%= f.input :amount, wrapper_html: { class: 'field validate--empty' }, input_html: { id: "dose-form-amount" } %>
              </div>
              <!-- measurement -->
              <div class="flex_fluid field">
                  <label for="dose_measurement_id">Measurement</label>
                  <select name="dose[measurement_id]" class="ui search dropdown">
                    <option value="none">- None -</option>
                    <% @measurements.each do |m|  %>
                    <option value="<%= m.id %>"><%= m.name %><%= " (#{m.abbrev})" if m.abbrev %></option>
                    <% end %>
                  </select>
                </div>
            </div>

          </div>
          <!-- form submit -->
          <div class="margin-top">
            <%= button_tag type: 'submit', class: 'ui blue icon button' do %>
            <i class="add icon"></i>
            Add Dose
            <% end %>
          </div>
        <% end %> <!-- /simple_form -->
      </div>
    </div>
    <!-- /mix doses -->


    <!-- edit instructions -->
    <div class="ui green ribbon label">
      <i class="caret right icon"></i>
      Mixing Details
    </div>
    <div class="ui basic segment">
      <%= simple_form_for @cocktail, method: :patch, html: { class: 'ui form' } do |f| %>
        <%= f.input :instructions, as: :text, wrapper_html: { class: 'field validate--empty' }, input_html: { rows: 16, placeholder: 'How do you mix the cocktail?' }, label_html: { class: 'sr-only' } %>
        <div class="margin-top">
          <%= f.submit "Update", class: 'ui green button' %>
        </div>
      <% end %>
    </div>

  </div>  <!-- /edit content segment -->

</div> <!-- /page ontainer -->

app/views/cocktails/index.html.erb
<h1 class="sr-only">Cocktails</h1>
<%= render partial: 'shared/site_banner', locals: { header: 'Cocktails' } %>
<div class="ui container">

    <!-- header -->
    <div class="ui secondary segment force--up flex-colrev-divide-middle margin-top margin-x flex-response--tablet_row">

      <div class="fill-width flex_grow margin-x">
        <%= render partial: 'shared/search_bar', locals: { action: cocktails_path, classes: 'fill-width', placeholder: 'Search cocktails...' } %>
      </div>

      <!-- actions right floated -->
      <div class="cocktail-index-actions mobile hidden">
        <div class="ui horizontal labeled icon menu">

          <!-- random -->
          <%= link_to random_cocktails_path, class: 'item' do %>
            <i class="violet question icon"></i>
            Random
          <% end %>

          <%= link_to new_cocktail_path, class: 'item' do %>
          <i class="yellow icon">
            <i class="icons">
              <i class="flask icon"></i>
              <i class="top right corner add icon"></i>
            </i>
          </i>
          Create
          <% end %>
        </div> <!-- /menu -->
      </div> <!-- /actions -->
    </div> <!-- /header -->

    <!-- search results -->
    <% if @search_results %>
      <h2 id="<%= @search_id %>-top" class="ui center aligned horizontal divider header">
        <div class="sub header">Search results for "<strong><em><%= @search_query %></em></strong>"</div>
      </h2>
      <div class="margin-x margin-bot padding-bot">
        <% if @search_results.any? %>
          <%= render partial: 'shared/cocktail_list', locals: { id: @search_id, cocktails: @search_results } %>
          <%= render partial: 'shared/pagination_menu', locals: { id: @search_id + "-pagination", items: @search_results, param_name: :search_page } %>
        <% else %>
          <div class="ui warning message">
            <span class="flex-center-middle inline margin-right">
              <i class="circular exclamation icon"></i>
            </span>
            <span>No results found for "<em><%= @search_query %></em>"</span>
          </div>
        <% end %>
      </div>
    <% end %>


    <!-- user associated cocktails -->
    <% if user_signed_in? %>
      <div class="margin-y">
        <div class="ui stackable grid">
          <div class="ten wide column margin-none">

            <!-- marked cocktails -->
            <div class="ui basic yellow segment">
              <%= render partial: 'shared/section_header', locals: { text: 'Saved Cocktails', as: 'h2', attached: true } %>
            </div>
            <% if @marked_cocktails %>
              <%= render partial: 'shared/cocktail_list_compact', locals: { cocktails: @marked_cocktails, header_size: 'md', description: true, description_size: 'md' } %>
              <div style="text-transform: uppercase; text-align: center">
                <%= link_to 'View all', user_path(current_user), class: 'ui yellow button' %>
              </div>
            <% else %>
              <div class='ui yellow message'>
                No saved cocktails. <%= link_to 'Find a random one.', random_cocktails_path %>
              </div>
            <% end %>

          </div>
          <div class="six wide column margin-none">

            <!-- user's cocktail recipes -->
            <div class="ui basic purple segment">
              <%= render partial: 'shared/section_header', locals: { text: 'Your Recipes', as: 'h2', attached: true } %>
            </div>
            <% if @user_cocktails %>
              <%= render partial: 'shared/cocktail_list_compact', locals: { cocktails: @user_cocktails, header_size: 'sm', description: true, description_size: 'sm' } %>
              <div style="text-transform: uppercase; text-align: center">
                <%= link_to 'View all', user_path(current_user), class: 'ui purple button' %>
              </div>
            <% else %>
              <div class='ui purple message'>
                You have no recipes. <%= link_to 'Create a cocktail.', new_cocktail_path %>
              </div>
            <% end %>

          </div>
        </div>
      </div>
    <% end %>

    <!-- classic -->
    <div class="margin-y">
      <div class="ui basic secondary segment">
        <%= render partial: 'shared/section_header', locals: { text: 'Classic Collection', as: 'h2', dividing: true } %>
        <%= render partial: 'shared/cocktail_badge_list', locals: { cocktails: @classic } %>
      </div>
    </div>

    <!-- custom -->
    <div id="<%= @custom_id %>-top" class="ui basic orange segment">
      <%= render partial: 'shared/section_header', locals: { text: 'Community Creations', as: 'h2', attached: true } %>
      <%= render partial: 'shared/cocktail_cards', locals: { id: @custom_id, cocktails: @custom } %>
      <%= render partial: 'shared/pagination_menu', locals: { id: @custom_id + "-pagination", items: @custom, param_name: :custom_page } %>
    </div>

</div>

app/views/cocktails/index.js.erb
// pagination ajax response

// update url
window.history.pushState({ path: '<%= @url %>'}, '', '<%= @url %>')

setTimeout(() => {
  <% if @change_search %>
    $('#<%= @search_id %>').replaceWith("<%= j render(partial: 'shared/cocktail_list', locals: { id: @search_id, cocktails: @search_results }) %>")
    $('#<%= @search_id %>-pagination').replaceWith("<%= j render(partial: 'shared/pagination_menu', locals: { id: @search_id + '-pagination', items: @search_results, param_name: :search_page }) %>")
    // window.scrollTo(0, $('#<%= @search_id %>-top').offset().top - 10)
  <% end %>

  <% if @change_custom %>
    $('#<%= @custom_id %>').replaceWith("<%= j render(partial: 'shared/cocktail_cards', locals: { id: @custom_id, cocktails: @custom }) %>")
    $('#<%= @custom_id %>-pagination').replaceWith("<%= j render(partial: 'shared/pagination_menu', locals: { id: @custom_id + '-pagination', items: @custom, param_name: :custom_page }) %>")
    // window.scrollTo(0, $('#<%= @custom_id %>-top').offset().top - 10)
  <% end %>
}, 200)

app/views/cocktails/mark.js.erb
<% if @errors.any? %>

  <% error_messages = "<ul class='list'><li>#{@errors.full_messages.join('</li><li>')}</li></ul>" %>
  $('#notifications-box').append("<%= render partial: 'shared/alert', locals: { title: 'Alert', message: error_messages } %>")

  jshelper.activateNotifications();

<% else %>

  $('#mark-link i').toggleClass('yellow grey outline')
  var label = $('#mark-link span')
  label.html(label.html().trim() == 'Save' ? 'Saved' : 'Save')

<% end %>

app/views/cocktails/new.html.erb
<div class="cover-image padding-y2" <%= render_bg_img(cl_image_path('bar.jpg'))%>>
  <div class="flex-col-middle padding-y">
    <i class="huge icons">
      <i class="inverted flask icon"></i>
      <i class="top right corner inverted add icon"></i>
    </i>
    <h1 class="ui center aligned inverted header">
      <em>Create A Cocktail</em>
    </h1>
  </div>
</div>

<div class="ui container">

  <div class="ui very padded secondary purple segment force--up">

    <!-- middle -->
    <div class="device-center">
      <!-- flash messages -->
      <% unless @cocktail.errors.empty? %>
      <div class="ui error message">
        <i class="close icon"></i>
        <div class="header">There were some errors with your submission</div>
        <ul class="list">
          <% @cocktail.errors.full_messages.each do |err| %>
          <li><%= err %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <!-- form -->
      <%= simple_form_for @cocktail, html: { id: 'cocktail-form', class: 'ui form' } do |f| %>
        <%= f.input :name, wrapper_html: { class: 'sixteen wide field validate--empty' } %>
        <%= f.input :description, as: :text, wrapper_html: { class: 'field' }, input_html: { placeholder: 'Introduce your cocktail with a brief description...'} %>
        <div class="flex-row">
          <%= f.input :photo, as: :file, wrapper_html: { class: 'field flex_fluid' }, input_html: { id: 'cocktail_photo', class: 'image-upload-preview' } %>
          <%= f.input :photo_cache, as: :hidden %>
          <div id="cocktail_photo-preview" class="img-sq-xs-circle flex_static margin-all hide"> </div>
        </div>
        <%= f.submit class: 'ui primary button', style: 'margin-top:30px;' %>
      <% end %>
    </div>

  </div> <!-- /segment -->

</div>

app/views/cocktails/publish.js.erb
<% if @cocktail.errors.any? %>

  <% error_messages = "<ul class='list'><li>#{@cocktail.errors.full_messages.join('</li><li>')}</li></ul>" %>
  $('#notifications-box').append("<%= render partial: 'shared/alert', locals: { title: 'Alert', message: error_messages } %>")

  jshelper.activateNotifications();

<% else %>

  $('#publish-link i').toggleClass('green grey')
  $('#publish-link span').html("<%= @cocktail.published ? 'Published' : 'Publish' %>")

<% end %>

app/views/cocktails/show.html.erb
<div class="cover-image">
  <!-- underlay -->
  <div class="background-underlay cocktail-banner-img">
    <img src="<%= @cocktail.image_path %>">
  </div>

  <!-- header -->

  <div class='ui container padding-y'>
    <div class="flex-row-divide-end padding-all">
      <!-- cocktail photo -->
      <div class="img-sq-circle cocktail-avatar margin-right flex_static mobile hidden">
        <img src="<%= @cocktail.image_path %>" alt="<%= @cocktail.name %>">
      </div>
      <!-- cocktail name, creator -->
      <div class="ui basic segment flex_fluid">
        <h1 class="ui huge inverted header margin-left">
          <%= @cocktail.name || 'Unnamed Cocktail' %>
          <div class="sub header">
            <%= render partial: 'shared/cocktail_meta', locals: { cocktail: @cocktail, anchors: true} %>
          </div>
        </h1>
      </div>

      <!-- actions -->
      <div class="ui vertical labeled icon menu flex_static">
        <!-- like -->
        <%= link_to mark_cocktail_path, id: 'mark-link', class: 'item' do %>
          <% saved = user_signed_in? && current_user.marked.include?(@cocktail) %>
          <i class="<%= saved ? 'yellow bookmark' : 'grey bookmark outline' %> icon"></i>
          <span>Save<%= saved ? 'd' : '' %></span>
        <% end %>
        <!-- remix cocktail -->
        <%= link_to remix_cocktail_path(@cocktail), method: :post, class: 'item' do %>
          <i class="purple icon">
            <i class="icons">
              <i class="flask icon"></i>
              <i class="top right corner random icon"></i>
            </i>
          </i>
          Remix
        <% end %>
        <!-- edit cocktail -->
        <% if current_user && current_user == @cocktail.user %>
          <%= link_to edit_cocktail_path(@cocktail), class: 'item' do %>
            <i class="orange icon">
              <i class="icons">
                <i class="flask icon"></i>
                <i class="top right corner edit icon"></i>
              </i>
            </i>
            Lab
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="ui container">

  <!-- content -->

  <div class="margin-x padding-bot">

    <!-- description -->
    <div class="padding-y margin-y">
      <div class="ui basic secondary padded purple segment">
        <p><%= @cocktail.description %></p>
      </div>
    </div>

    <!-- main content grid -->
    <div class="ui tablet reversed computer reversed stackable grid">

      <div class="five wide column">
        <div class="ui orange raised segment">
          <h3 class="ui center aligned dividing header">
            <div class="ui sub header">Ingredients</div>
          </h3>
          <div class="margin-left margin-bot">
            <% if @cocktail.doses.empty? %>
            <div>Nothing here yet!</div>
            <% else %>
            <ul class="ui list">
              <% @cocktail.doses.each do |dose| %>
              <li class="item">
                <%= stringify_dose_amount(dose, true) %>
                <%= dose.measurement ? ' of ' : ' ' %>
                <strong><%= dose.ingredient.name %></strong>
              </li>
              <% end %>
            </ul>
            <% end %>
          </div>
        </div>
      </div>

      <div class="eleven wide column">
        <div class="ui basic segment">
          <h3 class="sr-only">Instructions</h3>
          <%= @cocktail.instructions ? simple_format(@cocktail.instructions) : "No instructions yet." %>
        </div>
      </div>

    </div>
    <!-- /main content grid -->

    <!-- reviews -->
    <div class="ui horizontal divider sub header">
      <div class="ui sub header">Reviews</div>
    </div>

    <!-- all reviews -->
    <div class="ui basic segment">
      <div id="review-list" class="ui very relaxed divided icon list">
        <% if @cocktail.reviews.any? %>
          <% @cocktail.reviews.each do |r| %>
            <%= render partial: 'shared/review', locals: { review: r }  %>
          <% end %>
        <% else %>
          <div class="ui basic segment">No reviews yet.</div>
        <% end %>
      </div>
    </div>

    <!-- review form -->
    <% if user_signed_in? %>
      <% if @user_has_reviewed %>
        <!-- do not allow new review if user already reviewed -->
        <div class="ui message">
          <span class="flex-center-middle inline margin-right">
            <i class="circular exclamation icon"></i>
          </span>
          <span>You have already reviewed this cocktail. <%= link_to "Click here", edit_cocktail_review_path(@cocktail, @user_review) %> to edit your review</span>
        </div>
      <% else %>
        <%= render partial: 'shared/review_form', locals: { title: 'Write a review', method: :post, cocktail: @cocktail, review: @review } %>
      <% end %>
    <% else %>
      <!-- not logged in options -->
      <div class="ui yellow message">
        <span class="flex-center-middle inline margin-right">
          <i class="circular exclamation icon"></i>
        </span>
        <span>
          <%= link_to "Login", new_user_session_path %>
          or
          <%= link_to "Sign Up", new_user_registration_path %>
          to post a review.
        </span>
      </div>
    <% end %>

  </div> <!-- content -->

</div>