config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  get '/classics', to: 'pages#classics'
  get '/search', to: 'pages#search'

  resources :users, only: [:index, :show]

  resources :cocktails do
    get 'random', on: :collection
    member do
      post 'remix'
      get 'mark'
      patch 'publish'
    end
    resources :doses, only: [:create, :destroy]
    resources :reviews, except: [:new, :show]
  end

  match '*path' => 'errors#route_404', via: :all

end

app/views/shared/_alert.html.erb
<div class="ui warning icon message app-alert">
  <i class="exclamation triangle icon"></i>
  <i class="close icon"></i>
  <div class="content">
    <div class="header"><%= title %></div>
    <%= message %>
  </div>
</div>

app/views/shared/_cocktail_avatar.html.erb
<div class="img-sq-xxs-circle margin-right">
  <img src="<%= cocktail.image_path %>" alt="<%= cocktail.name %>">
</div>

app/views/shared/_cocktail_badge.html.erb
<%= link_to cocktail_path(cocktail), class: 'item cocktail-badge' do %>
  <div class="cocktail-badge-content flex-col-middle">
    <div class="img-sq-xxs-circle margin-bot">
      <img src="<%= cocktail.image_path %>" alt="<%= cocktail.name %>">
    </div>
    <h4 class="ui center aligned header">
      <div class="sub header">
        <%= cocktail.name %>
      </div>
    </h4>
  </div>
<% end %>

app/views/shared/_cocktail_badge_list.html.erb
<div class="ui horizontal selection list scrolling-width cocktail-badge-list">
  <% cocktails.each_with_index do |cocktail, index| %>
    <%= render partial: 'shared/cocktail_badge', locals: { cocktail: cocktail } %>
  <% end %>
</div>

app/views/shared/_cocktail_cards.html.erb
<div <%= "id=#{id}" if local_assigns[:id] %> class="ui doubling stackable center aligned four cards padding-x cocktail-cards">

  <% cocktails.each do |cocktail| %>
  <div class="card">
    <a class="image hover--zoom" href="<%= cocktail_path(cocktail) %>">
      <img src="<%= cocktail.image_path %>" alt="<%= cocktail.name %>">
    </a>
    <div class="content">
      <a href="<%= cocktail_path(cocktail) %>"class="header">
        <%= cocktail.name %>
      </a>
      <%= render partial: 'shared/cocktail_meta', locals: { cocktail: cocktail, anchors: true, show_reviews: true, show_marks: true } %>
      <div class="margin-top">
        <p class="color-reset">
          <%= cocktail.description.length > 99 ? cocktail.description[0...99] + '...' : cocktail.description %>
        </p>
      </div>
    </div>
  </div>
  <% end %>

</div>

app/views/shared/_cocktail_list_compact.html.erb
<div <%= "id=#{id}" if local_assigns[:id] %> class="ui relaxed middle aligned unstackable selection list">
  <% cocktails.each do |cocktail| %>
    <%= link_to cocktail_path(cocktail), class: 'item' do %>
      <img src="<%= cocktail.image_path %>" class="ui avatar image">
      <div class="content attach-relative">
        <div class="header text-briefline--<%= local_assigns[:header_size] ||= 'md' %>"><%= cocktail.name %></div>
        <%= render partial: 'shared/cocktail_meta', locals: { cocktail: cocktail } %>
        <% if local_assigns[:description] %>
          <div class="description text-briefline--<%= local_assigns[:description_size] ||= 'md' %>"><%= cocktail.description %></div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_cocktail_meta.html.erb
<% anchor_tag = local_assigns[:anchors] && anchors == true && cocktail.user != nil ? 'a' : 'span' %>

<div class="meta" style="padding-top: .5rem">
  <% if cocktail.reviews.any? %>
    <span>
      <%= cocktail.rating %>
      <i class="star icon"></i>
    </span>
  <% end %>
  <<%= anchor_tag %> href="<%= cocktail.user ? user_path(cocktail.user) : '#' %>">
    <div class='ui label'>
      @<%= cocktail.creator %>
    </div>
  </<%= anchor_tag %>>
  <% if local_assigns[:show_reviews] && show_reviews == true %>
    <span>
      <%= cocktail.reviews.any? ? cocktail.reviews.count : '0' %> review<%= 's' if cocktail.reviews.count != 1 %>
    </span>
  <% end %>
  <% if local_assigns[:show_marks] && show_marks == true && cocktail.marks.any? %>
    <span>
      <%= cocktail.marks.count %> like<%= 's' if cocktail.marks.count != 1 %>
    </span>
  <% end %>
  <% if current_user == cocktail.user && !cocktail.published %>
    <span>(Private)</span>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div id="navbar" class="ui top fixed menu">
  <div class="ui container">
    <div id="navbar-nav-actions" class="left menu">
      <%= link_to root_path, class: 'item' do %>
        <img src="<%= image_path('favicon/favicon.ico') %>" alt="Creative Cocktails">
      <% end %>
      <%= link_to "Cocktails", cocktails_path, class: "#{'active ' if controller_name == 'cocktails'}item" %>
      <%= link_to "Ingredients", ingredients_path, class: "#{'active ' if controller_name == 'ingredients'}item" %>
    </div>
    <div id="navbar-auth-actions" class="right menu">
      <% if user_signed_in? %>
        <%= link_to user_path(current_user), class: "#{'active ' if controller_name == 'users' && @user && @user == current_user}item" do %>
          <i class='user icon'></i>
          <%= current_user.name %>
        <% end %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'item' %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: 'item' %>
        <%= link_to "Sign Up", new_user_registration_path, class: 'item' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_notice.html.erb
<div class="ui info icon message app-notice">
  <i class="info circle icon"></i>
  <i class="close icon"></i>
  <div class="content">
    <div class="header"><%= title %></div>
    <%= message %>
  </div>
</div>

app/views/shared/_pagination_menu.html.erb
<div <%= "id=#{id}" if local_assigns[:id] %> class="flex-center padding-all">
  <%= will_paginate items, param_name: param_name ||= :page, class: "ui pagination menu", renderer: RemoteLinkPagination::LinkRenderer %>
</div>

app/views/shared/_review_form.html.erb
<div class="ui padded segment">
  <div class="ui top left attached label"><%= title %></div>
  <%= simple_form_for [cocktail, review], method: method, remote: false, html: { id: 'review-form', class: 'ui form' } do |f| %>
    <div class="two fields">
      <%= f.input :title, label: 'Summary', wrapper_html: { class: 'field validate--empty' } %>
      <%= f.input :rating, label: 'Rating (1-5)', wrapper_html: { class: 'field validate--empty' }, input_html: { step: 1, min: 1, max: 5 } %>
    </div>
    <%= f.input :text, as: :text, label: 'Detail', wrapper_html: { class: 'field' }, input_html: { rows: 3 } %>
    <%= f.submit "Post", class: 'ui yellow button' %>
  <% end %>
</div>

app/views/shared/_search_bar.html.erb
<%= form_with url: action, method: method ||= :get, local: true, class: "ui #{'transparent' if local_assigns[:transparent]} left icon input #{classes if local_assigns[:classes]}" do |f| %>
  <i class="search icon"></i>
  <%= f.text_field (param ||= :search), id: local_assigns[:id] ? id : param, placeholder: placeholder ||= 'Search' %>
<% end %>

app/views/shared/_section_header.html.erb
<% if attached ||= false %>
  <div class="ui top attached <%= color ||= '' %> label">
    <%= text %>
  </div>
<% else %>
  <<%= as ||= 'h2' %> class="ui center aligned large <%= color ||=  '' %> <%= local_assigns[:dividing] ? 'dividing' : '' %> sub header">
  <%= text %>
  </<%= as ||= 'h2' %>>
<% end %>

app/views/shared/_user_menu.html.erb
<% if user_signed_in? %>
  <%= link_to user_path(current_user), class: "#{'active ' if controller_name == 'users' && @user && @user == current_user}item" do %>
    <i class='user icon'></i>
    <%= current_user.name %>
  <% end %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'item' %>
<% else %>
  <%= link_to "Login", new_user_session_path, class: 'item' %>
  <%= link_to "Sign Up", new_user_registration_path, class: 'item' %>
<% end %>