config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  get '/classics', to: 'pages#classics'
  get '/search', to: 'pages#search'

  resources :users, only: [:index, :show]

  resources :cocktails do
    get 'random', on: :collection
    member do
      post 'remix'
      get 'mark'
      patch 'publish'
    end
    resources :doses, only: [:create, :destroy]
    resources :reviews, except: [:new, :show]
  end

  match '*path' => 'errors#route_404', via: :all

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :find_review, except: [:index, :create]

  after_action :verify_authorized, except: [:index, :create]

  def index
    @reviews = Review.where(cocktail: get_cocktail)
  end

  def create
    puts params
    @review = Review.new(strong_params)
    @review.user = current_user
    @review.cocktail = get_cocktail
    if @review.save
      redirect_to cocktail_path(@review.cocktail), notice: "Review posted!"
    else
      redirect_back fallback_location: cocktail_path(@review.cocktail), alert: "Failed to post review: #{@review.errors.full_messages.join(' ')}"
    end
  end

  def edit
    authorize @review
  end

  def update
    authorize @review
  end

  def destroy
    authorize @review
    if @review.destroy
      cocktail = get_cocktail
      redirect_to cocktail_path(cocktail), notice: "Your review for #{cocktail.name} was removed."
    else
      redirect_to request.referrer, alert: "Failed to delete review: #{@review.errors.full_messages.join(' ')}"
    end
  end

  private

  def get_cocktail
    Cocktail.find(params[:cocktail_id])
  end

  def find_review
    @review = Review.find(params[:id])
  end

  def strong_params
    params.require(:review).permit(:cocktail, :rating, :title, :text)
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<div class="ui basic container segment">

  <!-- cocktail info -->
  <div class="ui basic segment">
    <div class="ui basic secondary yellow segment">
      <div class="header">
        <div class="ui sub header">Reviewing: </div>
        <div class="ui basic segment">
          <div class="ui items">
            <%= render partial: 'shared/cocktail_item', locals: { cocktail: @review.cocktail } %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- review form -->
  <%= render partial: 'shared/review_form', locals: { title: 'Edit your review', method: :patch, cocktail: @review.cocktail, review: @review } %>

  <!-- delete review -->
  <div class="flex-center padding-all">
    <%= link_to cocktail_review_path(@review.cocktail, @review), method: :delete, class: 'ui compact basic red icon button', data: { confirm: 'Are you sure you want to delete your review?' } do %>
    <i class="trash icon"></i>
    Delete your review
    <% end %>
  </div>

</div>