config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  get '/classics', to: 'pages#classics'
  get '/search', to: 'pages#search'

  resources :users, only: [:index, :show]

  resources :cocktails do
    get 'random', on: :collection
    member do
      post 'remix'
      get 'mark'
      patch 'publish'
    end
    resources :doses, only: [:create, :destroy]
    resources :reviews, except: [:new, :show]
  end

  match '*path' => 'errors#route_404', via: :all

end

app/views/layouts/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path('favicon/apple-touch-icon.png') %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path('favicon/favicon-32x32.png') %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path('favicon/favicon-16x16.png') %>">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="<%= image_path('favicon/safari-pinned-tab.svg') %>" color="#fe9a76">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_footer.html.erb
<footer class="ui fluid container basic inverted segment footer">
  <div class='ui basic center aligned inverted segment'>
    <p>
      <h6 class="ui sub header" style="opacity:0.7">Sitemap</h6>
      <div class='ui inverted secondary compact vertical menu padding-top'>
        <%= render partial: 'layouts/sitemap_links' %>
      </div>
    </p>
    <p>
      <h6 class="ui sub header" style="opacity:0.7">Credits</h6>
      <br>Cocktail descriptions by Cat Wolinski via <%= link_to 'Vinepair', "https://vinepair.com/articles/50-most-popular-cocktails-world-2017/" %>
      <br>Classic recipes and images from <%= link_to 'Liquor.com', 'https://www.liquor.com/' %>
      <br>Stock photos from <%= link_to 'Unsplash', 'https://unsplash.com/' %>
      <br>Random user content generated by <%= link_to 'Faker', 'https://github.com/faker-ruby/faker' %>
    </p>
  </div>
  <div class='ui divider' style="max-width:360px;margin:auto"></div>
  <p class="ui center aligned tiny grey sub header" style="opacity: 0.7; font-size: 14px">
    Ruby on Rails — Semantic UI — PostGreSQL — Heroku
  </p>
  <div class="ui center aligned tiny grey sub header">
    Created by <%= link_to "mcli830", 'https://github.com/mcli830' %>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<div id="navbar" class="ui menu">
  <div class="ui container">

    <div id="navbar-nav-actions" class="left menu" style="flex-grow: 1">

      <!-- brand -->
      <%= link_to root_path, class: 'item' do %>
        <img src="<%= image_path('favicon/favicon.ico') %>" alt="Cocktail Craft">
      <% end %>

      <!-- left menu -->
      <%= link_to "Cocktails", cocktails_path, class: "#{'active ' if controller_name == 'cocktails' && action_name == 'index'}item mobile hidden" %>
      <%= link_to "Create", new_cocktail_path, class: "#{'active ' if controller_name == 'cocktails' && action_name == 'new'}item mobile hidden" %>
      <div class='item' style="flex-grow:1">
        <%= render partial: 'shared/search_bar', locals: { id: 'navbar_search', action: search_path, param: :query, transparent: true } %>
      </div>
    </div>

    <!-- right menu options -->
    <!-- mobile only -->
    <div id="navbar-auth-actions" class="right menu mobile only">
      <div class='ui dropdown item'>
        <i class='bars icon'></i>
        <!-- dropdown content -->
        <div class='menu' style="right:0;left:auto">
          <%= link_to 'Cocktails', cocktails_path, class: 'item' %>
          <%= link_to 'Create', new_cocktail_path, class: 'item' %>
          <div class='ui divider'></div>
          <%= render partial: 'shared/user_menu' %>
        </div>
      </div>
    </div>
    <!-- not mobile -->
    <div id="navbar-auth-actions" class="right menu mobile hidden">
      <%= render partial: 'shared/user_menu' %>
    </div>

  </div>
</div>

app/views/layouts/_sitemap_links.html.erb
<%= link_to 'Top', '#', class: 'ui sub header item' %>
<%= link_to 'Home', root_path, class: 'ui sub header item' %>
<%= link_to 'Cocktails', cocktails_path, class: 'ui sub header item' %>
<%= link_to 'Create A Cocktail', new_cocktail_path, class: 'ui sub header item' %>
<%= link_to 'Random Cocktail', random_cocktails_path, class: 'ui sub header item' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocktail Craft</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= tag :meta, name: :psjs, action: action_name, controller: controller_name %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/favicon' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <main>
      <%= render "layouts/navbar" %>
      <%= yield %>
      <%= render "shared/notifications" %>
    </main>

    <%= render partial: 'layouts/footer' %>

  </body>
</html>